### ISSUE TITLE
webtransport.Stream implementing net.Conn

### ISSUE THREAD

**Issue by aidansteele** [marten-seemann/webtransport-go#27]
Hi,

**Context**:

Thank you for a great library. I have started implementing a layer on top of webtransport-go (when HTTP/3 connectivity is available on the network) with a fallback to [`yamux`](https://github.com/hashicorp/yamux) over HTTP/1.1 upgraded connections (when HTTP/3 fails to connect). 

**Proposal**:

`yamux` multiplexed streams implement `net.Conn`. `webtransport.Stream` _almost_ implements `net.Conn` - it is missing `LocalAddr() net.Addr` and `RemoteAddr() net.Addr`. These could be implemented by just returning the values of the underlying `webtransport.Session`. This would be valuable to me as then I can have a wrapper that returns `net.Conn` in either scenario.

Do you see any reason why this would be undesirable? Was not implementing these methods intentional, or just a use case that had yet to be considered?

**Comment by marten-seemann** [comment]
This would _suggest_ that having a local and a remote address is a property of the stream, not of the session, which is it not.

Can you just wrap the `webtransport.Stream` yourself, and add those methods in your application?

**Comment by aidansteele** [comment]
That's a reasonable point. I can wrap this easily enough in my own application and it avoids adding confusion/complexity to this library. 

I think I'll close this for now, thank you!
