### ISSUE TITLE
ReadAll() Implementation for bidirectional stream

### ISSUE THREAD

**Issue by moksh-samespace** [marten-seemann/webtransport-go#42]
Quic-go support ReadAll() for bidirectional stream. Is there any way to achieve this in webtransport-go?

**Comment by marten-seemann** [comment]
That's standard library functionality.

**Comment by moksh-samespace** [comment]
Can you help with an example how I can achieve this
`
stream, err := conn.AcceptStream(conn.Context())
if err != nil {
	fmt.Println("Session closed, not accepting more bidi streams:", err)
	break
}

for {
	buf := make([]byte, 1024)
	n, err := stream.Read(buf)
	if err != nil {
		fmt.Printf("Error reading from bidi stream %v\n", err)
		break
	}
}
`
