### ISSUE TITLE
Typescript bindings for webtransport

### ISSUE THREAD

**Issue by unicomp21** [marten-seemann/webtransport-go#50]
I realize this is all about golang, but connecting from the browser in typescript projects would be nice.  Anybody got ideas?  Next time I'll post questions like this in discussions, once they are enabled.

**Comment by marten-seemann** [comment]
> I realize this is all about golang, but connecting from the browser in typescript projects would be nice.

Nice, but you're right, it's completely unrelated to a WebTransport implementation in Go.
